export const SET_COUNTRIES = 'SET_COUNTRIES';
export const VISITED_COUNTRY = 'VISITED_COUNTRY';
export const SEARCH_COUNTRIES = 'SEARCH_COUNTRIES';
export const FILTER_COUNTRIES = 'FILTERED_COUNTRIES';
export const REMOVE_FILTERED = 'REMOVE_FILTERED';
export const REMOVE_VISITED = 'REMOVE_VISITED';
